Models/Player.cs
using _66bitPractice.Data;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace _66bitPractice.Models
{
	public class Player
	{
		[Key]
		public int PlayerId { get; set; }

		public string PictureURL { get; set; }

		public string Name { get; set; }

		public string Surname { get; set; }

		public Gender Gender { get; set; }

		public DateTime BirthDate { get; set; }

		public Country Country { get; set; }


		public int TeamId { get; set; }

		[ForeignKey("TeamId")]
		public Team Team { get; set; }
	}
}

Models/Team.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace _66bitPractice.Models
{
    public class Team
    {
        [Key]
        public int Id { get; set; }
        [Required, Display(Name="Team Name")]
        public string Name { get; set; }
        public List<Player> Players { get; set; }
    }
}

Controllers/PlayerController.cs
using _66bitPractice.Data.HubPog;
using _66bitPractice.Data.Services;
using _66bitPractice.Data.Utils;
using _66bitPractice.Data.ViewModels;
using _66bitPractice.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace _66bitPractice.Controllers
{
	public class PlayerController : Controller
	{
		private readonly IPlayerService playerService;
		private readonly ITeamService teamService;

		public PlayerController(IPlayerService playerService, ITeamService teamService)
		{
			this.playerService = playerService;
			this.teamService = teamService;
		}

		public async Task<IActionResult> Show()
		{
			var modelData = (await playerService.GetAllPlayers()).Select(p => new PlayerVM(p));
			await UpdateViewBagData();
			return View(modelData);
		}

		public async Task<IActionResult> Edit(int id)
		{
			var player = await playerService.GetPlayerById(id);
			if (player == null)
			{
				return View("NotFound");
			}
			await UpdateViewBagData();
			return View(new NewPlayerVM(player));
		}

		[HttpPost]
		public async Task<IActionResult> Update(int id, NewPlayerVM player)
		{
			if (!ModelState.IsValid)
			{
				await UpdateViewBagData();
				return View(nameof(Edit),player);
			}
			await playerService.Update(id, player);
			return RedirectToAction(nameof(Show));
		}

		[HttpPost]
		public async Task<IActionResult> AddNew(NewPlayerVM player)
		{
			if (!ModelState.IsValid || player.TeamId == 0)
			{
				await UpdateViewBagData();
				return View("Add", player);
			}
			await playerService.Add(player);
			return RedirectToAction(nameof(Show));
		}

		public async Task<IActionResult> Add()
		{
			await UpdateViewBagData();
			return View();
		}

		public async Task<IActionResult> Delete(int id)
		{
			await playerService.Delete(id);
			await UpdateViewBagData();
			return RedirectToAction(nameof(Show));
		}


		public async Task<IActionResult> Search(string searchString)
		{
			var allPlayers = await playerService.GetAllPlayers();

			if (!string.IsNullOrEmpty(searchString))
			{
				var filteredResultNew = allPlayers.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase)
				|| string.Equals(n.Surname, searchString, StringComparison.CurrentCultureIgnoreCase))
					.Select(p => new PlayerVM(p))
					.ToList();

				return View("Show", filteredResultNew);
			}
			return View("NotFound");
		}

		[HttpGet]
		public IEnumerable<int> GetPlayersIds()
		{
			return (playerService.GetAllPlayers().Result).Select(p => p.PlayerId);
		}

		[HttpGet]
		public ActionResult GetPlayerPartialById(int id)
		{
			return PartialView("_PlayerTemplatePV", new PlayerVM(playerService.GetPlayerById(id).Result));
		}

		private async Task UpdateViewBagData()
		{
			ViewBag.Teams = await teamService.GetAllTeams();
		}
	}
}

Controllers/TeamController.cs
using _66bitPractice.Data.Services;
using _66bitPractice.Data.ViewModels;
using _66bitPractice.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace _66bitPractice.Controllers
{
	public class TeamController : Controller
	{
		private readonly ITeamService service;

		public TeamController(ITeamService service)
		{
			this.service = service;
		}

		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddNewTeam(NewTeamVM team)
		{
			await service.Add(team);
			return RedirectToAction("Add", "Player");
		}

		[HttpGet]
		public IActionResult GetTeamFormPV()
		{
			return PartialView("_TeamFormValuesPV");
		}
	}
}

Views/Player/Add.cshtml
@using _66bitPractice.Data;
@using _66bitPractice.Data.ViewModels;
@model NewPlayerVM

@{
	ViewData["Title"] = "Add Your Professional;";
}

<div class="text-center">
	<h1 class="display-4">Professional</h1>
	<p>He is footballer.</p>
	<div>
		<form model="post" asp-controller="Player" asp-action="AddNew">
			@await Html.PartialAsync("_PlayerFormValuesPV",Model)
		</form>
	</div>
	<div class="">
		<div style="display:none;" id="form-placeholder">
			<h1>Add New Team</h1>
			<form id="team-form" model="post" asp-controller="Team" asp-action="AddNewTeam">
				<div id="team-form-values">
					@await Html.PartialAsync("_TeamFormValuesPV", new NewTeamVM())
				</div>
				<div class="form-group text-white">
					<input class="btn btn-success" id="team-add-btn" type="submit" value="Add it!" />
				</div>
			</form>
		</div>
	</div>
</div>

@section Scripts{
	<script>
		function changeVisibility(visible) {
			var $teamForm = $('#team-form-values');
			var placeHolder = document.getElementById("form-placeholder");
			if (visible) {
				placeHolder.style.display = "block";
			}
			else {
				placeHolder.style.display = "none";
			}
		}

		$("#player-team-select").change(function () {
			changeVisibility(this.value === "add new");
		});

		$('team-add-btn').click(function () {
			var teamForm = $('#team-form-values');
			('#form-placeholder').style.display = "none";
		});
	</script>
}

Views/Player/AltShow.cshtml
@model IEnumerable<Player>
@{
    ViewData["Title"] = "Yet another Page With All Players!";

    string GetTeamName(Team team)
    {
        return team == null ? "Not in any team" : team.Name;
    }
}

<div class="text-center">
    <h1 class="display-4">Best football players</h1>
    <div class="row">
        @foreach(var item in Model)
        {
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title">
                                        @item.Surname @item.Name
                                        <a class="btn btn-outline-primary float-right" asp-action="Edit" asp-route-id="@item.PlayerId">
                                            <i class="bi bi-pencil-square"></i> Edit
                                        </a>
                                    </h5>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@item.PictureURL" width="100%" alt="@item.Name">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text"><b>Gender: </b>@item.Gender.ToString()</p>
                                <p class="card-text"><b>Birth Date: </b>@item.BirthDate.ToString("dd MMM yyyy")</p>
                                <p class="card-text"><b>Team: </b>@GetTeamName(item.Team)</p>
                                <p class="card-text"><b>Country: </b>@item.Country</p>
                                @*<p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                                <p class="card-text ">
                                    <b>Status: </b>
                                    @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                    {
                                        <span class="badge bg-success text-white">AVAILABLE</span>
                                    }
                                    else if (DateTime.Now > item.EndDate)
                                    {
                                        <span class="badge bg-danger text-white">EXPIRED</span>
                                    }
                                    else
                                    {
                                        <span class="badge bg-primary text-white">UPCOMING</span>
                                    }
                                </p>*@

                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer ">
                                <p class="card-text">
                                    @*<a class="btn btn-outline-primary float-right" asp-action="Edit" asp-route-id="@item.PlayerId">
                                        <i class="bi bi-pencil-square"></i> Edit
                                    </a>*@
                                   
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Player/Edit.cshtml
@using _66bitPractice.Data.ViewModels;
@using _66bitPractice.Data;
@model NewPlayerVM

@{
	ViewData["Title"] = "Edit Your Professional";
}

<div class="text-center">
	<h1 class="display-4">Professional</h1>
	<p>His is footballer.</p>
	<div>
		<form model ="post" asp-controller="Player" asp-action="Update" asp-route-id="@Model.PlayerId">
			@await Html.PartialAsync("_PlayerFormValuesPV", Model)
		</form>
	</div>
</div>

Views/Player/NotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div>
    <h1>
        Player Could not be found
    </h1>
    <div class=" bi bi-emoji-frown"></div>
</div>

Views/Player/Show.cshtml
@using System.Reflection;
@using System.ComponentModel;
@using System.ComponentModel.DataAnnotations;
@using Microsoft.AspNetCore.Components;
@using Microsoft.AspNetCore.SignalR.Client;
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@using _66bitPractice.Controllers;
@using _66bitPractice.Data.Services;
@using _66bitPractice.Models;
@using _66bitPractice.Data.ViewModels;

@model IEnumerable<PlayerVM>
@{
	ViewData["Title"] = "Page With All Players!";
}

<div class="text-center">
	<h1 class="display-4">Best football players</h1>
	<div class="row">
		<div class="col-sm-9 offset-md-1">

			<table class="table">
				<thead>
					<tr>

						@foreach (var item in typeof(PlayerVM).GetProperties()
								.Select(prop => prop.GetCustomAttribute<DisplayAttribute>())
								.Where(displayAttr => displayAttr != null))
						{
							<th>@item.GetName()</th>
						}
						<th></th>
					</tr>
				</thead>
				<tbody id="PlayersTable">
					@foreach (var item in Model)
					{
						@await Html.PartialAsync("_PlayerTemplatePV", item)
					}
				</tbody>
				<tr>
					<td></td>
				</tr>


			</table>

		</div>
	</div>
</div>
<div class="text-white">
	<a asp-controller="Player" asp-action="Add" class="btn btn-success bottom-right"><i class="bi bi-plus-circle"></i>Add new</a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
	$(document).ready(function () {
		let connection = new signalR.HubConnectionBuilder().withUrl("/PlayersHub").build();
		connection.start();
		console.log("Start of js code");
		connection.on("Notify", function () {
			loadPlayers();
		});

		//loadPlayers();

		function loadPlayers() {
			$.ajax({
				url: 'GetPlayersIds',
				async: true,
				method: "GET",
				success: (result) => {
					$("#PlayersTable").empty();
					for (var i = 0; i < result.length; i++) {
						console.log(result[i]);
						$.ajax({
							url: 'GetPlayerPartialById',
							async: true,
							method: "GET",
							data: { 'id': result[i] },
							success: function (responce) {
								console.log(responce);
								$('#PlayersTable').append(responce);
							},
							error: function (err) {
								console.log(err);
							}
						});
					}
				},
				error: (error) => {
					console.log(error)
				}
			})
		}
	})
</script>

Views/Player/_PlayerFormValuesPV.cshtml
@using _66bitPractice.Data.ViewModels;
@using _66bitPractice.Data;
@model NewPlayerVM
@{
	IEnumerable<SelectListItem> GetTeams()
	{
		foreach (var team in ViewBag.Teams)
		{
			yield return new SelectListItem(team.Name, team.Id.ToString());
		}
	}
}

<div>
	<ul>
		<div class="form-group">
			<img class="player-face rounded-circle" id="PicturePreview" />
		</div>
		<li class="form-group">
			<label class="control-label col-md-2" asp-for="@Model.PictureURL"></label>
			<input class=" col-md-1 " asp-for="@Model.PictureURL" />
			<span class="text-danger col-md-1" asp-validation-for="@Model.PictureURL"></span>
		</li>
		<li class="form-group">
			<label class="control-label col-md-2" asp-for="@Model.Name"></label>
			<input class=" col-md-1 " asp-for="@Model.Name" />
			<span class="text-danger" asp-validation-for="@Model.Name"></span>
		</li>
		<li class="form-group">
			<label class="control-label col-md-2" asp-for="Surname"></label>
			<input class=" col-md-1 " asp-for="Surname" />
			<span class="text-danger" asp-validation-for="Surname"></span>
		</li>
		<li class="form-group">
			<label class="control-label col-md-2" asp-for="Gender"></label>
			<select class="col-md-1" id="GenderSelect" asp-for="Gender" asp-items="@(Html.GetEnumSelectList<Gender>())">
				<option disabled selected="selected" value="">Please select</option>
			</select>
			<span class="text-danger" asp-validation-for="Gender"></span>
		</li>
		<li class="form-group">
			<label class="control-label col-md-2" asp-for="BirthDate"></label>
			<input class="col-md-1" asp-for="BirthDate" type="date" placeholder="From" />
			<span class="text-danger" asp-validation-for="BirthDate"></span>
		</li>
		<li class="form-group">

			<label class="control-label col-md-2" asp-for="@Model.TeamId"></label>
			<select id="player-team-select" class="col-md-1" asp-for="@Model.TeamId" asp-items="@GetTeams()">
				<option disabled="disabled" selected="selected" value="not selected">Please select</option>

				<option value ="add new">Add New</option>
			</select>
			<span class="text-danger" asp-validation-for="@Model.TeamId"></span>
		</li>
		<li class="form-group">
			<label class="control-label col-md-2" asp-for="Country"></label>
			<select class="col-md-1" asp-for="Country" asp-items="@(Html.GetEnumSelectList<Country>())">
				<option disabled selected="selected" value="">Please select</option>
			</select>
			<span class="text-danger" asp-validation-for="Country"></span>
		</li>
	</ul>

	<input class="btn btn-outline-success" type="submit" value="Submit" />
</div>

Views/Player/_PlayerTemplatePV.cshtml
@using _66bitPractice.Data.ViewModels;
@model PlayerVM

@{
	string GetTeamName(string team)
	{
		return team == null ? "Not in any team" : team;
	}
}

<tr>
	<td class="align-middle">
		<img src="@Model.PictureURL" class="rounded-circle player-face" alt="Profile Picture">
	</td>
	<td class="align-middle">@Model.Name</td>
	<td class="align-middle">@Model.Surname</td>
	<td class="align-middle">@Model.Gender</td>
	<td class="align-middle">@Model.BirthDate.ToShortDateString()</td>
	<td class="align-middle">@GetTeamName(Model.Team)</td>
	<td class="align-middle">@Model.Country</td>
	<td class="align-middle">

		<a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.PlayerId"><i class="bi bi-pencil-square"></i>Edit</a>
		<a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@Model.PlayerId"><i class="bi bi-trash"></i>Delete</a>
	</td>
</tr>

Views/Player/_TeamFormValuesPV.cshtml
@using _66bitPractice.Data.ViewModels;
@model NewTeamVM

<div>
	<div class="form-group">
		<label class="control-label">@Html.DisplayNameFor(item => item.Name)</label>
		<input type="text" asp-for="Name" />
		<span class="text-danger" asp-validation-for="Name"></span>
	</div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - _66bitPractice</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css?version=1.0" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Player" asp-action="Show">_66bitPractice</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Add">Add</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Show">Show</a>
						</li>
					</ul>
				</div>
				<form class="form-inline my-2 my-lg-0 search-form" asp-controller="Player" asp-action="Search">
					<input name="searchString" type="text" class="form-control" placeholder="Find a player" />
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
				</form>
			</div>
		</nav>
	</header>
	<div class="container-fluid">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			My First ASP.NET Project!
		</div>
	</footer>
	<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/signalr/dist/browser/signalr.js"></script>
	<script src="~/js/chat.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Team/_TeamFormValuesPV.cshtml
@using _66bitPractice.Data.ViewModels;
@model NewTeamVM

<div>
	<div class="form-group">
		<label class="control-label">@Html.DisplayNameFor(item => item.Name)</label>
		<input type="text" asp-for="Name" />
		<span class="text-danger" asp-validation-for="Name"></span>
	</div>
</div>